--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cooldogepm/BedrockEconomy
build-by-default: true
branches:
- main
- pm5
projects:
  BedrockEconomy:
    path: ""
    libs:
      - src: cooldogepm/libSQL/libSQL
        version: ^0.2.3
        branch: pm5
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
    lint:
      phpstan: false
#      syntaxError: false
...


